PROCESS BEFORE OUTPUT.
  MODULE STATUS_0101.
  MODULE INIT_SCREEN.

PROCESS AFTER INPUT.
  MODULE POPUP_EXIT AT EXIT-COMMAND.
  MODULE USER_COMMAND_0101.

PROCESS ON VALUE-REQUEST.
  FIELD GV_MATNR MODULE GET_MATERIAL.
