PROCESS BEFORE OUTPUT.
  MODULE STATUS_0100.
  MODULE INIT_VALUE.            " Defalt값 세팅
  MODULE GET_SO_DATA.           " 판매오더 헤더 데이터 불러옴
  MODULE ACTIVE_TAB.            " 탭 스트립 세팅
  MODULE INIT_PROCESS_CONTROL.  " 스크린 세팅

  CALL SUBSCREEN SUB_AREA INCLUDING SY-REPID GV_SUBSCREEN.

PROCESS AFTER INPUT.
  CALL SUBSCREEN SUB_AREA.

  MODULE EXIT AT EXIT-COMMAND.  " Exit 모듈
  MODULE PROCESS_TAB.           " 탭 스트립
  MODULE USER_COMMAND_0100.     " 사용자 지정 OKCODE 처리

PROCESS ON VALUE-REQUEST.       " Search Help(F4) 달기
  FIELD : GV_CHNL_FROM   MODULE F4_CHNL,
          GV_CHNL_TO     MODULE F4_CHNL,
          GV_BPCODE_FROM MODULE F4_BP,
          GV_BPCODE_TO   MODULE F4_BP.

